### PR TITLE
Fix build on GHC 9.2

### PR DESCRIPTION
**Pull request by amesgen**
Depends on https://github.com/haskell/aeson/issues/885

Fixes this compilation error:
```
src/Deriving/Aeson/Stock.hs:27:1: error:
    • Uninferrable type variable k0 in
      the type synonym right-hand side: CustomJSON @{[k0]} ('[] @k0)
    • In the type declaration for ‘Vanilla’
   |
27 | type Vanilla = CustomJSON '[]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

### CODE REVIEW

**Comment by Bodigrim** [comment]
As a Hackage trustee I made a matching revision:
https://hackage.haskell.org/package/deriving-aeson-0.2.7/revisions/
